version : '3'

services:
  mysql:
    image: mysql:5.7
    container_name: dev_pmf_mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_conf/my.cnf:/etc/my.cnf
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: please_change_me
      MYSQL_ROOT_PASSWORD: please_change_me
      MYSQL_DATABASE: pmf
    ports:
    - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pmf_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8181:80
